NAMES = ["Paige", "Kira", "Leia", "John", "Hector", "Natalie", "Roman", "Audrey", "Marlee", "Andrea", "Tripp", "Heath",
         "Ryland", "Monica", "Rodney", "Brennen", "Cayden", "Ross", "Aydan", "Yael", "Brodie", "Jaylin", "Alondra",
         "Joel", "Zion", "Lindsay", "Johnny", "Chana", "Edith", "Anabella", "Alivia", "Jadiel", "Jaylee", "Romeo",
         "Jaylene", "Shea", "Wayne", "Lyric", "Lainey", "Rihanna", "Declan", "Victor", "Blake", "Kamora", "Dane",
         "Reece", "Elaine", "Dominique", "Autumn", "Phillip", "Jeremy", "Chad", "Alex", "Abby", "Parker", "Nancy",
         "Sanai", "Alexa", "Edward", "Phoenix", "Shania", "Chaz", "Lia", "Devan", "Elyse", "Nelson", "Skylar",
         "Emerson", "Damon", "Derrick", "Courtney", "Angie", "Geovanni", "Sullivan", "Lillian", "Mercedes", "Alisson",
         "Luciana", "Emmanuel", "Mina", "Ronan", "Boston", "Simeon", "Kennedi", "Kaylah", "Garrett", "Anderson",
         "Mohammed", "Cash", "Alexis", "Briana", "Raymond", "Sabrina", "Londyn", "Melissa", "Stacy", "Addyson",
         "Harrison", "Ronald", "Zane"]
